# curl --location --request POST 'http://localhost:7071/api/AddWaiter'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "firstName": "Chris P the third.",
#    "lastName": "Bacon the second",
#    "birthday": "2001-12-12",
#    "address": "123 drive",
#    "phone": "111-111-111",
#    "title": "Boss"
#}'
# https://waitless-functions-2.azurewebsites.net/api/Add-User?code=qbKCJmMn8zHVga9kZ/p9Uwh03U9RKOrKGmfUdWL8sMsMOuVZJ12DKQ==
POST http://localhost:7071/api/Add-User
Content-Type: application/json

{
    "firstName": "Chris P the third.",
    "lastName": "Bacon the second",
    "birthday": "2001-12-12",
    "address": "123 drive",
    "phone": "111-111-111",
    "title": "Boss"
}

###

