# curl --location --request POST 'http://localhost:7071/api/Get-Uncompleted-Tasks-Based-On-User'
#--header 'Content-Type: application/json'
#--data-raw '{
#	employeeId:"2121"
#}'
POST https://waitless-functions-2.azurewebsites.net/api/Get-Active-Tasks-Based-On-User?code=61hVnYrUocwE8RdgHiwZgqzMjN9/gO4DdiBsS2a2uU1JxvhAxQOOHQ==
#https://waitless-functions-2.azurewebsites.net/api/Get-Active-Tasks-Based-On-User?code=61hVnYrUocwE8RdgHiwZgqzMjN9/gO4DdiBsS2a2uU1JxvhAxQOOHQ==
Content-Type: application/json

{
  employeeID: "2121"
}

###
## SAMPLE OUTPUT BELOW
#[
#  {
#    "taskID": "1009",
#    "employeeID": "2127",
#    "status": "Active",
#    "title": "Take out the trash",
#    "description": "We need the trash to be taken out",
#    "tableNumber": "OT"
#  },
#  {
#    "taskID": "1013",
#    "employeeID": "2127",
#    "status": "Active",
#    "title": "test seting",
#    "description": "this is a test sending task",
#    "tableNumber": "A1"
#  }
#]

