# curl --location --request POST 'http://localhost:7071/api/Get-Uncompleted-Tasks-Based-On-User'
#--header 'Content-Type: application/json'
#--data-raw '{
#	employeeId:"2121"
#}'
POST https://waitless-functions-2.azurewebsites.net/api/Get-Active-Tasks-Based-On-User?code=61hVnYrUocwE8RdgHiwZgqzMjN9/gO4DdiBsS2a2uU1JxvhAxQOOHQ==
#https://waitless-functions-2.azurewebsites.net/api/Get-Active-Tasks-Based-On-User?code=61hVnYrUocwE8RdgHiwZgqzMjN9/gO4DdiBsS2a2uU1JxvhAxQOOHQ==
Content-Type: application/json

{
  employeeID: "2121"
}

###

