# curl --location --request POST 'http://localhost:7071/api/Get-Completed-Tasks-Based-On-User'
#--header 'Content-Type: application/json'
#--data-raw '{
#	employeeId:"2121"
#}'
POST http://localhost:7071/api/Get-Inactive-Tasks-Based-On-User
# https://waitless-functions-2.azurewebsites.net/api/Get-Inactive-Tasks-Based-On-User?code=Ciyv62I26diHC58R7NFzBxZsMeiGIEe5IiLVuavOJo7ZzZR/L465eQ==
Content-Type: application/json

{
  employeeId: "2121"
}

###

