# curl --location --request POST 'http://localhost:7071/api/Get-Uncompleted-Tasks-Based-On-User'
#--header 'Content-Type: application/json'
#--data-raw '{
#	employeeId:"2121"
#}'
POST http://localhost:7071/api/Get-Active-Tasks-Based-On-User
Content-Type: application/json

{
  employeeId: "2121"
}

###

