# curl --location --request POST 'http://localhost:7071/api/Get-Tasks-Based-On-User'
#--header 'Content-Type: application/json'
#--data-raw '{
#	employeeId:"2124"
#}'
# https://waitless-functions-2.azurewebsites.net/api/Get-Tasks-Based-On-User?code=o8MBEVnmIFF2gBhUMabe8ppV9tpNhqduW1EaKGHAnFTuaeM9xYzvew==
POST http://localhost:7071/api/Get-Tasks-Based-On-User
Content-Type: application/json

{
  employeeId: "2124"
}

###

