# curl --location --request POST 'http://localhost:7071/api/Get-Employee'
#--header 'Content-Type: application/json'
#--data-raw '{
#	employeeId: "2124"
#}'
POST http://localhost:7071/api/Get-Employee
Content-Type: application/json

{
  employeeId: "2124"
}

###


